import argparse
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from vurecomp import vudec
from vurecomp.cfg import build_cfg


def load(manifest_dir):
    with open(os.path.join(manifest_dir, "manifest.json"), encoding="utf-8") as f:
        man = json.load(f)
    for p in man["programs"]:
        with open(os.path.join(manifest_dir, p["image"]), "rb") as f:
            p["bytes_"] = f.read()
    return man


def decode_check(man):
    up_bad = collections.Counter()
    lo_bad = collections.Counter()
    up_hist = collections.Counter()
    lo_hist = collections.Counter()
    pairs = 0
    for p in man["programs"]:
        code = vudec.decode_image(p["bytes_"], p["code_lo"], p["code_hi"])
        for pc in sorted(code):
            pair = code[pc]
            pairs += 1
            up_hist[pair.upper.name] += 1
            if pair.upper.kind == "bad":
                up_bad[pair.up_word & 0x3F] += 1
            if pair.lower is None:
                lo_hist["<I-bit immediate>"] += 1
            else:
                lo_hist[pair.lower.name] += 1
                if pair.lower.kind == "bad":
                    lo_bad[(pair.lo_word >> 25) & 0x7F] += 1

    print("decoded %d instruction pairs across %d images"
          % (pairs, len(man["programs"])))
    print("  upper: %d distinct mnemonics, %d unknown"
          % (len(up_hist), sum(up_bad.values())))
    print("  lower: %d distinct mnemonics, %d unknown"
          % (len(lo_hist), sum(lo_bad.values())))
    for what, bad in (("upper", up_bad), ("lower", lo_bad)):
        for enc, n in bad.most_common():
            print("    UNKNOWN %s opcode 0x%02X  x%d" % (what, enc, n))
    print("\n  upper mnemonics by frequency:")
    for name, n in up_hist.most_common():
        print("    %-10s %8d" % (name, n))
    print("\n  lower mnemonics by frequency:")
    for name, n in lo_hist.most_common():
        print("    %-16s %8d" % (name, n))
    return sum(up_bad.values()) + sum(lo_bad.values())


def stats(man):
    total_insns = sum(p["instructions"] for p in man["programs"])
    print("%d images, %s interpreted instructions attributed\n"
          % (len(man["programs"]), f"{total_insns:,}"))
    seen = {}
    for p in sorted(man["programs"], key=lambda q: -q["instructions"]):
        code = vudec.decode_image(p["bytes_"], p["code_lo"], p["code_hi"])
        entries = [e["pc"] for e in p["entries"] if e["count"]]
        cfg = build_cfg(code, entries)
        share = 100.0 * p["instructions"] / total_insns if total_insns else 0.0
        cover = 100.0 * cfg.reachable_pairs / len(code) if code else 0.0
        print("%s  %4d pairs  %5.1f%% of interpreted work" %
              (p["crc"][:12], len(code), share))
        print("      entries %s -> %d blocks, %d/%d pairs reached (%.0f%%)" %
              (", ".join("%04X" % e for e in entries),
               len(cfg.blocks), cfg.reachable_pairs, len(code), cover))
        if cfg.call_returns:
            print("      %d BAL return sites, %d JR blocks -- a JR compiles to "
                  "a switch over %d block starts"
                  % (len(cfg.call_returns), len(cfg.indirect_blocks),
                     len(cfg.blocks)))
        seen[p["crc"]] = cfg
    ranked = sorted(man["programs"], key=lambda q: -q["instructions"])
    run = 0.0
    print("\ncumulative share of interpreted work, hottest first:")
    for p in ranked[:8]:
        run += 100.0 * p["instructions"] / total_insns if total_insns else 0
        print("    %s  %5.1f%%" % (p["crc"][:12], run))
    return 0


def generate(man, out_path):
    from vurecomp.emit import emit_program, Unsupported

    bodies, table, skipped = [], [], []
    seen = {}
    dropped = 0
    for p in sorted(man["programs"], key=lambda q: -q["instructions"]):
        entries = [e["pc"] for e in p["entries"] if e["count"]]
        try:
            body, cfg, reach, words, blocks = emit_program(
                p["crc"], p["bytes_"], entries, p["code_lo"], p["code_hi"])
        except Unsupported as e:
            skipped.append((p["crc"], str(e)))
            continue
        sig = (tuple(reach), tuple(words), tuple(blocks))
        if sig in seen:
            table[seen[sig]][2] += p["instructions"]
            dropped += 1
            continue
        seen[sig] = len(table)
        bodies.append(body)
        table.append([p["crc"], len(cfg.blocks), p["instructions"], len(reach)])

    total = sum(q["instructions"] for q in man["programs"]) or 1
    covered = sum(t[2] for t in table)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/vurecomp -- do not edit.\n"
                " *\n"
                " * VU1 microprograms lifted to C.  Included by ps2_vu.c so\n"
                " * that the interpreter's static helpers -- vu_add4,\n"
                " * vu_set_flags, vu_fdiv_issue and the rest -- are the ones\n"
                " * this code calls.  Sharing them is what keeps the two\n"
                " * implementations from drifting apart, which is the whole\n"
                " * premise of checking one against the other.\n"
                " *\n"
                " * %d of %d programs lifted, %.1f%% of measured interpreted work.\n"
                % (len(table), len(man["programs"]), 100.0 * covered / total))
        for crc, why in skipped:
            f.write(" * skipped %s: %s\n" % (crc[:12], why))
        f.write(" */\n\n")
        for b in bodies:
            f.write(b)
            f.write("\n\n")
        f.write("/* A program is identified by the code it will execute, not\n"
                " * by the whole 16 KB image -- see the signature note in\n"
                " * emit.py.  npairs is how many pairs must match. */\n"
                "static const struct {\n"
                "    const unsigned short *pc;\n"
                "    const unsigned int *w;\n"
                "    unsigned npairs;\n"
                "    int (*fn)(ps2_vu *, u32, u32, u32 *, u32 *, u32 *);\n"
                "} vu1_recomp_table[] = {\n")
        for crc, nblocks, insns, npairs in table:
            f.write("    { vu1_sig_pc_%s, vu1_sig_w_%s, %u, vu1_prog_%s },"
                    "  /* %d blocks */\n" % (crc, crc, npairs, crc, nblocks))
        f.write("};\n"
                "#define VU1_RECOMP_N "
                "((int)(sizeof vu1_recomp_table / sizeof vu1_recomp_table[0]))\n")

    print("wrote %s" % out_path)
    print("  %d programs lifted (%d census images deduplicated onto them), "
          "%d skipped" % (len(table), dropped, len(skipped)))
    print("  %.1f%% of interpreted work covered" % (100.0 * covered / total))
    for crc, nblocks, insns, npairs in table:
        print("    %s  %4d blocks  %4d pairs  %5.1f%% of work"
              % (crc[:12], nblocks, npairs, 100.0 * insns / total))
    for crc, why in skipped:
        print("  skipped %s: %s" % (crc[:12], why))
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="vurecomp")
    ap.add_argument("--programs", default="out/vu_programs",
                    help="directory holding manifest.json (default %(default)s)")
    ap.add_argument("--decode-check", action="store_true")
    ap.add_argument("--stats", action="store_true")
    ap.add_argument("-o", "--output", metavar="FILE",
                    help="generate the C include for ps2_vu.c")
    args = ap.parse_args(argv)

    if not os.path.exists(os.path.join(args.programs, "manifest.json")):
        raise SystemExit(
            "No census at %s/manifest.json.\n"
            "Record one by running the game with PS2_VU_CENSUS=1 set."
            % args.programs)
    man = load(args.programs)

    rc = 0
    if args.decode_check:
        rc |= decode_check(man)
    if args.stats:
        rc |= stats(man)
    if args.output:
        rc |= generate(man, args.output)
    if not (args.decode_check or args.stats or args.output):
        ap.print_help()
    return rc


if __name__ == "__main__":
    sys.exit(main())
