import csv
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SCENE_NAMES = {
    "1.18": "mission, in flight",
    "16.4": "hangar",
    "17.6": "title / main menu",
    "17.7": "main menu",
    "17.8": "main menu",
    "15.2": "briefing",
    "16.2": "hangar entry",
    "23.2": "pre-mission",
    "22.8": "mission load",
    "22.7": "movie",
    "18.4": "movie",
}


def load_symbols():
    names = {}
    path = os.path.join(ROOT, "config", "game_symbols.txt")
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 2:
            names[int(parts[0], 16)] = parts[1]
    return names


def row_name(r, names):
    func = int(r["func"], 16) if r["func"] else 0
    site = int(r["site"], 16) if r["site"] else 0
    emitter = int(r["emitter"])
    if emitter < 8:
        return r["name"].replace(";", ",")
    if r["via"] == "3":
        return "%s (writer)" % names.get(site, "sub_%08X" % site)
    base = names.get(func, "sub_%08X" % func)
    return "%s+0x%X" % (base, site - func)


def main(paths):
    names = load_symbols()
    out = []
    out.append("# Render map\n")
    out.append("Generated by `tools/render_map.py` from render-map CSVs written by "
               "`PS2_RENDER_MAP` runs (`runtime/src/rn/rn_census.c`). An **emitter** "
               "is the engine call that opened a packet range -- the caller of "
               "`COt::_Open`, a 2D helper's caller, or a packet writer nested in "
               "such a range (`runtime/include/rn.h`). Pixels are primitive area "
               "clipped to the scissor, before depth test or blending: who asks "
               "for the pixels, not who wins them.\n")
    for path in paths:
        rows = list(csv.DictReader(open(path, encoding="utf-8", errors="replace")))
        scenes = defaultdict(list)
        for r in rows:
            scenes[r["scene"]].append(r)
        total_px = sum(float(r["pixels"]) for r in rows)
        named_px = sum(float(r["pixels"]) for r in rows
                       if int(r["emitter"]) >= 8 or int(r["emitter"]) == 1)
        out.append("\n## `%s`\n" % os.path.relpath(path, ROOT).replace("\\", "/"))
        native_px = sum(float(r.get("pixels_native") or 0) for r in rows)
        out.append("%.0f pixels over the run; **%.2f%%** attributed to a named "
                   "emitter (a call site, or DrawCtrl's own flush); **%.2f%%** drawn "
                   "by native passes (native VU1 meshes are not GS primitives and are "
                   "not in these numbers at all).\n"
                   % (total_px, 100.0 * named_px / total_px if total_px else 0.0,
                      100.0 * native_px / total_px if total_px else 0.0))
        order = sorted(scenes, key=lambda s: -sum(float(r["pixels"]) for r in scenes[s]))
        for s in order:
            srows = scenes[s]
            spx = sum(float(r["pixels"]) for r in srows)
            if spx < 0.01 * total_px and s not in SCENE_NAMES:
                continue
            frames = max(int(r["frames"]) for r in srows)
            snative = sum(float(r.get("pixels_native") or 0) for r in srows)
            out.append("\n### Scene %s%s -- %d frames, %.2f%% native\n" % (
                s, " (%s)" % SCENE_NAMES[s] if s in SCENE_NAMES else "", frames,
                100.0 * snative / spx if spx else 0.0))
            out.append("| share | emitter | px/frame | native | tris | sprites | lines | "
                       "targets |\n|---:|---|---:|---:|---:|---:|---:|---|")
            for r in sorted(srows, key=lambda r: -float(r["pixels"])):
                share = 100.0 * float(r["pixels"]) / spx if spx else 0.0
                if share < 0.05:
                    continue
                px = float(r["pixels"])
                nat = 100.0 * float(r.get("pixels_native") or 0) / px if px else 100.0
                out.append("| %.1f%% | `%s` | %.0f | %.0f%% | %s | %s | %s | %s |" % (
                    share, row_name(r, names), float(r["pixels_per_frame"]), nat,
                    r["tris"], r["sprites"], r["lines"], r["rt_slots"]))
            out.append("")
    dst = os.path.join(ROOT, "docs", "RENDER_MAP.md")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="\n") as fp:
        fp.write("\n".join(out) + "\n")
    print("wrote %s" % dst)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: python tools/render_map.py <render-map.csv> [...]")
    main(sys.argv[1:])
